-- Psych Learning Wiki — Supabase schema for shared scheduler state.
--
-- Run this once, whole, in the Supabase dashboard: SQL Editor → New query → paste → Run.
-- It is idempotent, so re-running after a change is safe.
--
-- What lives here and why: per CLAUDE.md the *content* (readings, item source) is git, and the app
-- owns the *scheduling state*. Putting that state in Postgres instead of review_state.json is what
-- lets the phone and the laptop share one queue — grade an item on the train and the Streamlit app
-- at home already knows it isn't due. Local review_state.json / review_log.csv keep being written as
-- a git-tracked snapshot (see apps/sync_supabase.py), they just stop being the source of truth.
--
-- Two tables, mirroring the two local files:
--   review_state  one row per item per user — the SM-2 record. Mutable.
--   review_log    one row per attempt. Append-only; the calibration history.
--
-- Column names deliberately avoid `interval` and `last`, which are Postgres keywords that would
-- need quoting at every call site. The clients map them back to the local JSON keys.

-- ---------------------------------------------------------------- state

create table if not exists public.review_state (
  user_id       uuid        not null default auth.uid() references auth.users (id) on delete cascade,
  item_id       text        not null,
  ease          real        not null default 2.5,
  interval_days integer     not null default 0,
  reps          integer     not null default 0,
  due_date      date        not null default current_date,
  last_reviewed date,
  updated_at    timestamptz not null default now(),
  primary key (user_id, item_id)
);

comment on table public.review_state is
  'SM-2 scheduling state, one row per item per user. Mirrors review_state.json.';

-- The hot query is "what is due for me today", on every app open.
create index if not exists review_state_due_idx
  on public.review_state (user_id, due_date);

-- ---------------------------------------------------------------- log

create table if not exists public.review_log (
  id                   bigint generated by default as identity primary key,
  user_id              uuid        not null default auth.uid() references auth.users (id) on delete cascade,
  ts                   timestamptz not null,
  item_id              text        not null,
  type                 text,
  bloom_level          text,
  cluster              text,
  predicted_confidence integer,
  outcome              text        not null check (outcome in ('correct', 'shaky', 'missed')),
  interval_before      integer,
  interval_after       integer,
  ease                 real,
  reps                 integer,
  time_taken_s         real,
  client               text        not null default 'web',
  -- Makes seeding idempotent: re-pushing review_log.csv cannot duplicate rows, because an attempt
  -- is identified by who/what/when. Second resolution is enough — you cannot grade the same item
  -- twice in the same second.
  unique (user_id, item_id, ts)
);

comment on table public.review_log is
  'Append-only attempt history. Mirrors review_log.csv; feeds the calibration view.';

create index if not exists review_log_recent_idx
  on public.review_log (user_id, ts desc);

-- ---------------------------------------------------------------- row-level security

alter table public.review_state enable row level security;
alter table public.review_log   enable row level security;

-- The web app ships the anon key in client code — that is what it is designed for. These policies
-- are the actual security boundary: a request can only ever touch rows whose user_id matches the
-- JWT it presented. Without them the anon key would be a public read/write handle on the table.
drop policy if exists "own review_state" on public.review_state;
create policy "own review_state" on public.review_state
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- The log is history: readable and appendable, never rewritable. No update or delete policy exists,
-- so those are denied by default even for the owner.
drop policy if exists "read own review_log" on public.review_log;
create policy "read own review_log" on public.review_log
  for select using (auth.uid() = user_id);

drop policy if exists "append own review_log" on public.review_log;
create policy "append own review_log" on public.review_log
  for insert with check (auth.uid() = user_id);

-- ---------------------------------------------------------------- record one attempt

-- One round trip per graded item instead of two, and atomic: the state advance and the log entry
-- land together or not at all. SM-2 itself stays in the clients (docs/sm2.js, apps/scheduler.py) —
-- it has to, because the app computes the next interval while offline and syncs later — so this
-- function stores what it is told rather than recomputing.
create or replace function public.record_attempt(
  p_item_id              text,
  p_outcome              text,
  p_ease                 real,
  p_interval_days        integer,
  p_reps                 integer,
  p_due_date             date,
  p_last_reviewed        date,
  p_ts                   timestamptz,
  p_type                 text default null,
  p_bloom_level          text default null,
  p_cluster              text default null,
  p_predicted_confidence integer default null,
  p_interval_before      integer default null,
  p_time_taken_s         real default null,
  p_client               text default 'web'
) returns void
language plpgsql
security invoker           -- runs as the caller, so RLS above still applies. Never security definer.
set search_path = public
as $$
begin
  insert into public.review_state as s
    (user_id, item_id, ease, interval_days, reps, due_date, last_reviewed, updated_at)
  values
    (auth.uid(), p_item_id, p_ease, p_interval_days, p_reps, p_due_date, p_last_reviewed, now())
  on conflict (user_id, item_id) do update set
    ease          = excluded.ease,
    interval_days = excluded.interval_days,
    reps          = excluded.reps,
    due_date      = excluded.due_date,
    last_reviewed = excluded.last_reviewed,
    updated_at    = now();

  insert into public.review_log
    (user_id, ts, item_id, type, bloom_level, cluster, predicted_confidence, outcome,
     interval_before, interval_after, ease, reps, time_taken_s, client)
  values
    (auth.uid(), p_ts, p_item_id, p_type, p_bloom_level, p_cluster, p_predicted_confidence,
     p_outcome, p_interval_before, p_interval_days, p_ease, p_reps, p_time_taken_s, p_client)
  -- A queued offline attempt can be replayed after it already succeeded; swallow the duplicate
  -- rather than failing the whole flush.
  on conflict (user_id, item_id, ts) do nothing;
end;
$$;

comment on function public.record_attempt is
  'Atomically advance an item''s SM-2 state and append its attempt. Used by the web app and the '
  'Streamlit runner so both surfaces write identically.';
